### ISSUE TITLE
Dask vs Prefect-Dask

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#17]
Which option might be better to use here? I saw that Don implemented Dask separately but since Prefect already has dask integration should we consider dask separately?

**Comment by leewujung** [comment]
@lsetiawan -- could you provide some insights into this? Thanks!

**Comment by lsetiawan** [comment]
You can see a little comment here: https://github.com/OSOceanAcoustics/echoflow/blob/main/echoflow/stages/level0.py#L41-L44

The reason that I implemented dask separatey was because echopype used dask under the hood, which this is problematic if you're using the dask task runner, since you can open up a dask client underneath a dask task runner. However this PR https://github.com/OSOceanAcoustics/echopype/pull/1042, which is in the latest version of echopype, got rid of this weirdness, so I'm curious now as to how it works out with the dask task runner. I'd say if you can, the option of using the `prefect-dask` is probably a better choice if it works!

**Comment by Sohambutala** [comment]
Thank you @lsetiawan and @leewujung! The code works fine with prefect-dask, so I will go ahead with this for now.

**Comment by lsetiawan** [comment]
So glad to hear! 😄
