### ISSUE TITLE
Missing environment.yaml file for conda

### ISSUE THREAD

**Issue by Sohambutala** [OSOceanAcoustics/echoflow#7]
Need to add the environment.yaml file to set up the environment correctly instead of using pip install .[all] command to make sure there is uniformity.

**Comment by leewujung** [comment]
I recommend the following:
- put together a `requirements.txt file` and provide instructions for how to create a conda environment using this file -- see [here](https://echopype.readthedocs.io/en/latest/contributing.html#installation-for-echopype-development) for example from echopype
   - note you should use the `-e` option when using pip so you don't run into problems like in #4 
- you can have separate `requirements.txt` and `requirements-dev.txt` files so that you separate out packages needed for the package itself, and packages needed for development (e.g. pytest, pre-commit, etc)
- once there is a first release, for demo notebooks, you can set up an `environment.yml` file for installing `echoflow` as a package in an environment to run the notebooks, something like [this](https://github.com/OSOceanAcoustics/echopype-examples/tree/main/binder).
